{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of IPython.utils.ipstruct failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/utils/ipstruct.py\", line 117, in __setattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: attr __class__ is a protected member of class Struct.\n",
      "]\n",
      "[autoreload of IPython.core.display failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of IPython.core.interactiveshell failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: do_up() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of prompt_toolkit.cache failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'SimpleCache' object layout differs from 'SimpleCache'\n",
      "]\n",
      "[autoreload of prompt_toolkit.filters.cli failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: <lambda>() requires a code object with 0 free vars, not 2\n",
      "]\n",
      "[autoreload of prompt_toolkit.history failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of prompt_toolkit.keys failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'Keys' object layout differs from 'Keys'\n",
      "]\n",
      "[autoreload of prompt_toolkit.key_binding.vi_state failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'InputMode' object layout differs from 'InputMode'\n",
      "]\n",
      "[autoreload of prompt_toolkit.key_binding.bindings.scroll failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/key_binding/bindings/scroll.py\", line 10, in <module>\n",
      "    from prompt_toolkit.layout.utils import find_window_for_buffer_name\n",
      "ImportError: cannot import name 'find_window_for_buffer_name' from 'prompt_toolkit.layout.utils' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/utils.py)\n",
      "]\n",
      "[autoreload of prompt_toolkit.layout.containers failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of prompt_toolkit failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/__init__.py\", line 16, in <module>\n",
      "    from .interface import CommandLineInterface\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/interface.py\", line 19, in <module>\n",
      "    from .application import Application, AbortAction\n",
      "ImportError: cannot import name 'AbortAction' from 'prompt_toolkit.application' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/__init__.py)\n",
      "]\n",
      "[autoreload of IPython.utils.generics failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: inspect_object() requires a code object with 2 free vars, not 4\n",
      "]\n",
      "[autoreload of IPython.terminal.debugger failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/debugger.py\", line 17, in <module>\n",
      "    from prompt_toolkit.shortcuts import create_prompt_application\n",
      "ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/__init__.py)\n",
      "]\n",
      "[autoreload of IPython.terminal.prompts failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: write_format_data() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of IPython.terminal.interactiveshell failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py\", line 20, in <module>\n",
      "    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output\n",
      "ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/__init__.py)\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "!pip install -q xgboost\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from numpy import loadtxt\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n",
    "from sklearn.metrics import mean_squared_error as MSE\n",
    "import boto3\n",
    "from sagemaker import get_execution_role\n",
    "import sagemaker\n",
    "\n",
    "# Use SageMaker\n",
    "SageMaker = True\n",
    "\n",
    "# Use back-test files\n",
    "back_test = False\n",
    "if back_test:\n",
    "  bt_frag = '-back'\n",
    "else:\n",
    "  bt_frag = ''\n",
    "\n",
    "# Set scaled boolean\n",
    "sclaled_on = True\n",
    "# Set XGBoost params \n",
    "full_params = True\n",
    "\n",
    "if not SageMaker:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    #!ls \"/content/drive/My Drive/LSTM Futures\"\n",
    "    #!cp '/content/drive/My Drive/LSTM Futures/Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv' 'Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv'\n",
    "    #!cp '/content/drive/My Drive/LSTM Futures/daily-granular' + bt_frag + '.csv' 'daily-granular' + bt_frag + '.csv'\n",
    "    EminiSP = pd.read_csv('/content/drive/My Drive/LSTM Futures/Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv')\n",
    "    EminiSPpredict = pd.read_csv('/content/drive/My Drive/LSTM Futures/daily-granular' + bt_frag + '.csv')\n",
    "else:\n",
    "    sagemaker_session = sagemaker.Session()\n",
    "    role = get_execution_role()\n",
    "    bucket='eminisp500vbloise'\n",
    "    train_data_key = 'Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv'\n",
    "    inference_data_key = 'daily-granular' + bt_frag + '.csv'\n",
    "    train_data_location = 's3://{}/{}'.format(bucket, train_data_key)\n",
    "    inference_data_location = 's3://{}/{}'.format(bucket, inference_data_key)\n",
    "    EminiSP = pd.read_csv(train_data_location)\n",
    "    EminiSPpredict = pd.read_csv(inference_data_location)\n",
    "\n",
    "X = EminiSP.copy()\n",
    "X.drop(['date-1', 'time-1', 'time-2', 'time-3', 'time-4', 'time-5', 'outcome', 'b_outcome'], axis=1, inplace=True) #,'percent-change-1', 'percent-change-2', 'percent-change-3'\n",
    "Y = EminiSP.pop('b_outcome')\n",
    "EminiSPpredict.drop(['date-1', 'time-1', 'time-2', 'time-3', 'time-4', 'time-5'], axis=1, inplace=True) #,'percent-change-1', 'percent-change-2', 'percent-change-3'\n",
    "\n",
    "print(X.head())\n",
    "print(X.shape)\n",
    "\n",
    "print(Y.head())\n",
    "print(Y.shape)\n",
    "\n",
    "print(EminiSPpredict.head())\n",
    "print(EminiSPpredict.shape)\n",
    "\n",
    "# split data into X and y\n",
    "#X = dataset[:,0:25]\n",
    "#Y = dataset[:,25]\n",
    "# split data into train and test sets\n",
    "seed = 7\n",
    "test_size = 0.33\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)\n",
    "# Scaling the data\n",
    "# encode class values as integers\n",
    "encoder = LabelEncoder()\n",
    "encoder.fit(Y)\n",
    "encoded_y = encoder.transform(Y)\n",
    "encoder.fit(y_train)\n",
    "encoded_y_train = encoder.transform(y_train)\n",
    "encoder.fit(y_test)\n",
    "encoded_y_test = encoder.transform(y_test)\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "Target_scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "Feature_scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "\n",
    "X_train_scaled = Feature_scaler.fit_transform(np.array(X_train))\n",
    "X_test_scaled = Feature_scaler.fit_transform(np.array(X_test))\n",
    "\n",
    "y_train_scaled = Target_scaler.fit_transform(np.array(encoded_y_train).reshape(-1,1))\n",
    "y_test_scaled = Target_scaler.fit_transform(np.array(encoded_y_test).reshape(-1,1))\n",
    "EminiSPpredict_scaled = Feature_scaler.fit_transform(np.array(EminiSPpredict))\n",
    "\n",
    "# fit model no training data\n",
    "# Defaults\n",
    "# XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,\n",
    "#       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=10,\n",
    "#       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,\n",
    "#       objective='binary:logistic', reg_alpha=0, reg_lambda=1,\n",
    "#       scale_pos_weight=1, seed=0, silent=True, subsample=1)\n",
    "if full_params:\n",
    "  model = XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.05,\n",
    "       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=10,\n",
    "       min_child_weight=1, missing=1, n_estimators=100, nthread=-1,\n",
    "       objective='binary:logistic', reg_alpha=0, reg_lambda=1,\n",
    "       scale_pos_weight=1, seed=0, subsample=1, use_label_encoder=False, eval_metric='logloss')\n",
    "else:\n",
    "  model = XGBClassifier()\n",
    "if not sclaled_on:\n",
    "  model.fit(X_train, encoded_y_train)\n",
    "  # make predictions for test data\n",
    "  y_pred = model.predict(X_test)\n",
    "else:\n",
    "  model.fit(X_train_scaled, encoded_y_train)\n",
    "  # make predictions for test data\n",
    "  y_pred = model.predict(X_test_scaled)\n",
    "predictions = [round(value) for value in y_pred]\n",
    "# evaluate predictions\n",
    "accuracy = accuracy_score(encoded_y_test, predictions)\n",
    "print(\"Accuracy: %.2f%%\" % (accuracy * 100.0))\n",
    "if not sclaled_on:  \n",
    "  # Predict the model\n",
    "  pred = model.predict(EminiSPpredict)\n",
    "  print(\"Prediction : % f\" %(pred))\n",
    "  # RMSE Computation\n",
    "  #rmse = np.sqrt(MSE(y_test, pred))\n",
    "  #print(\"RMSE : % f\" %(rmse))\n",
    "else:\n",
    "  # scaled\n",
    "  pred = model.predict(EminiSPpredict_scaled)\n",
    "  pred_rescaled = Target_scaler.inverse_transform(pred.reshape(1,-1))\n",
    "  print(\"Prediction : % f\" %(pred_rescaled))\n",
    "  # RMSE Computation\n",
    "  #rmse = np.sqrt(MSE(y_test_scaled, pred))\n",
    "  #print(\"RMSE : % f\" %(rmse))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of IPython.utils.ipstruct failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/utils/ipstruct.py\", line 117, in __setattr__\n",
      "    raise AttributeError(\n",
      "AttributeError: attr __class__ is a protected member of class Struct.\n",
      "]\n",
      "[autoreload of IPython.core.display failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of IPython.core.interactiveshell failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: do_up() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of prompt_toolkit.cache failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'SimpleCache' object layout differs from 'SimpleCache'\n",
      "]\n",
      "[autoreload of prompt_toolkit.filters.cli failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: <lambda>() requires a code object with 0 free vars, not 2\n",
      "]\n",
      "[autoreload of prompt_toolkit.history failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of prompt_toolkit.keys failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'Keys' object layout differs from 'Keys'\n",
      "]\n",
      "[autoreload of prompt_toolkit.key_binding.vi_state failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 317, in update_class\n",
      "    update_property),\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 280, in update_instances\n",
      "    old_obj = getattr(old, key)\n",
      "TypeError: __class__ assignment: 'InputMode' object layout differs from 'InputMode'\n",
      "]\n",
      "[autoreload of prompt_toolkit.key_binding.bindings.scroll failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/key_binding/bindings/scroll.py\", line 10, in <module>\n",
      "    from prompt_toolkit.layout.utils import find_window_for_buffer_name\n",
      "ImportError: cannot import name 'find_window_for_buffer_name' from 'prompt_toolkit.layout.utils' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/utils.py)\n",
      "]\n",
      "[autoreload of prompt_toolkit.layout.containers failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: __init__() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of prompt_toolkit failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/__init__.py\", line 16, in <module>\n",
      "    from .interface import CommandLineInterface\n",
      "  File \"/usr/local/lib/python3.9/site-packages/prompt_toolkit/interface.py\", line 19, in <module>\n",
      "    from .application import Application, AbortAction\n",
      "ImportError: cannot import name 'AbortAction' from 'prompt_toolkit.application' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/__init__.py)\n",
      "]\n",
      "[autoreload of IPython.utils.generics failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: inspect_object() requires a code object with 2 free vars, not 4\n",
      "]\n",
      "[autoreload of IPython.terminal.debugger failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/debugger.py\", line 17, in <module>\n",
      "    from prompt_toolkit.shortcuts import create_prompt_application\n",
      "ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/__init__.py)\n",
      "]\n",
      "[autoreload of IPython.terminal.prompts failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 410, in superreload\n",
      "    # IPython connectivity\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 302, in update_class\n",
      "    update_generic(old.fdel, new.fdel)\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 347, in update_generic\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 266, in update_function\n",
      "ValueError: write_format_data() requires a code object with 1 free vars, not 0\n",
      "]\n",
      "[autoreload of IPython.terminal.interactiveshell failed: Traceback (most recent call last):\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n",
      "    if do_reload:\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 613, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 855, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"/usr/local/lib/python3.9/site-packages/IPython/terminal/interactiveshell.py\", line 20, in <module>\n",
      "    from prompt_toolkit.shortcuts import create_prompt_application, create_eventloop, create_prompt_layout, create_output\n",
      "ImportError: cannot import name 'create_prompt_application' from 'prompt_toolkit.shortcuts' (/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/__init__.py)\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "!pip install -q xgboost\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from numpy import loadtxt\n",
    "from xgboost import XGBClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score\n",
    "from sklearn.metrics import mean_squared_error as MSE\n",
    "import boto3\n",
    "from sagemaker import get_execution_role\n",
    "import sagemaker\n",
    "\n",
    "# Use SageMaker\n",
    "SageMaker = True\n",
    "\n",
    "# Use back-test files\n",
    "back_test = False\n",
    "if back_test:\n",
    "  bt_frag = '-back'\n",
    "else:\n",
    "  bt_frag = ''\n",
    "\n",
    "# Set scaled boolean\n",
    "sclaled_on = True\n",
    "# Set XGBoost params \n",
    "full_params = True\n",
    "\n",
    "if not SageMaker:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    #!ls \"/content/drive/My Drive/LSTM Futures\"\n",
    "    #!cp '/content/drive/My Drive/LSTM Futures/Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv' 'Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv'\n",
    "    #!cp '/content/drive/My Drive/LSTM Futures/daily-granular' + bt_frag + '.csv' 'daily-granular' + bt_frag + '.csv'\n",
    "    EminiSP = pd.read_csv('/content/drive/My Drive/LSTM Futures/Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv')\n",
    "    EminiSPpredict = pd.read_csv('/content/drive/My Drive/LSTM Futures/daily-granular' + bt_frag + '.csv')\n",
    "else:\n",
    "    sagemaker_session = sagemaker.Session()\n",
    "    role = get_execution_role()\n",
    "    bucket='eminisp500vbloise'\n",
    "    train_data_key = 'Micro-Emini-SP500-MES-F-granular' + bt_frag + '.csv'\n",
    "    inference_data_key = 'daily-granular' + bt_frag + '.csv'\n",
    "    train_data_location = 's3://{}/{}'.format(bucket, train_data_key)\n",
    "    inference_data_location = 's3://{}/{}'.format(bucket, inference_data_key)\n",
    "    EminiSP = pd.read_csv(train_data_location)\n",
    "    EminiSPpredict = pd.read_csv(inference_data_location)\n",
    "\n",
    "X = EminiSP.copy()\n",
    "X.drop(['date-1', 'time-1', 'time-2', 'time-3', 'time-4', 'time-5', 'outcome', 'b_outcome'], axis=1, inplace=True) #,'percent-change-1', 'percent-change-2', 'percent-change-3'\n",
    "Y = EminiSP.pop('b_outcome')\n",
    "EminiSPpredict.drop(['date-1', 'time-1', 'time-2', 'time-3', 'time-4', 'time-5'], axis=1, inplace=True) #,'percent-change-1', 'percent-change-2', 'percent-change-3'\n",
    "\n",
    "print(X.head())\n",
    "print(X.shape)\n",
    "\n",
    "print(Y.head())\n",
    "print(Y.shape)\n",
    "\n",
    "print(EminiSPpredict.head())\n",
    "print(EminiSPpredict.shape)\n",
    "\n",
    "# split data into X and y\n",
    "#X = dataset[:,0:25]\n",
    "#Y = dataset[:,25]\n",
    "# split data into train and test sets\n",
    "seed = 7\n",
    "test_size = 0.33\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)\n",
    "# Scaling the data\n",
    "# encode class values as integers\n",
    "encoder = LabelEncoder()\n",
    "encoder.fit(Y)\n",
    "encoded_y = encoder.transform(Y)\n",
    "encoder.fit(y_train)\n",
    "encoded_y_train = encoder.transform(y_train)\n",
    "encoder.fit(y_test)\n",
    "encoded_y_test = encoder.transform(y_test)\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "\n",
    "Target_scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "Feature_scaler = MinMaxScaler(feature_range=(0, 1))\n",
    "\n",
    "X_train_scaled = Feature_scaler.fit_transform(np.array(X_train))\n",
    "X_test_scaled = Feature_scaler.fit_transform(np.array(X_test))\n",
    "\n",
    "y_train_scaled = Target_scaler.fit_transform(np.array(encoded_y_train).reshape(-1,1))\n",
    "y_test_scaled = Target_scaler.fit_transform(np.array(encoded_y_test).reshape(-1,1))\n",
    "EminiSPpredict_scaled = Feature_scaler.fit_transform(np.array(EminiSPpredict))\n",
    "\n",
    "# fit model no training data\n",
    "# Defaults\n",
    "# XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,\n",
    "#       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=10,\n",
    "#       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,\n",
    "#       objective='binary:logistic', reg_alpha=0, reg_lambda=1,\n",
    "#       scale_pos_weight=1, seed=0, silent=True, subsample=1)\n",
    "if full_params:\n",
    "  model = XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=0.05,\n",
    "       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=10,\n",
    "       min_child_weight=1, missing=1, n_estimators=100, nthread=-1,\n",
    "       objective='binary:logistic', reg_alpha=0, reg_lambda=1,\n",
    "       scale_pos_weight=1, seed=0, subsample=1, use_label_encoder=False, eval_metric='logloss')\n",
    "else:\n",
    "  model = XGBClassifier()\n",
    "if not sclaled_on:\n",
    "  model.fit(X_train, encoded_y_train)\n",
    "  # make predictions for test data\n",
    "  y_pred = model.predict(X_test)\n",
    "else:\n",
    "  model.fit(X_train_scaled, encoded_y_train)\n",
    "  # make predictions for test data\n",
    "  y_pred = model.predict(X_test_scaled)\n",
    "predictions = [round(value) for value in y_pred]\n",
    "# evaluate predictions\n",
    "accuracy = accuracy_score(encoded_y_test, predictions)\n",
    "print(\"Accuracy: %.2f%%\" % (accuracy * 100.0))\n",
    "if not sclaled_on:  \n",
    "  # Predict the model\n",
    "  pred = model.predict(EminiSPpredict)\n",
    "  print(\"Prediction : % f\" %(pred))\n",
    "  # RMSE Computation\n",
    "  #rmse = np.sqrt(MSE(y_test, pred))\n",
    "  #print(\"RMSE : % f\" %(rmse))\n",
    "else:\n",
    "  # scaled\n",
    "  pred = model.predict(EminiSPpredict_scaled)\n",
    "  pred_rescaled = Target_scaler.inverse_transform(pred.reshape(1,-1))\n",
    "  print(\"Prediction : % f\" %(pred_rescaled))\n",
    "  # RMSE Computation\n",
    "  #rmse = np.sqrt(MSE(y_test_scaled, pred))\n",
    "  #print(\"RMSE : % f\" %(rmse))"
   ]
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "aee8b7b246df8f9039afb4144a1f6fd8d2ca17a180786b69acc140d282b71a49"
  },
  "kernelspec": {
   "display_name": "Python 3.9.5 64-bit",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
